export const DEFAULT_PERMISSIONS=['storage'];
export function normalizePath(p){const out=[];for(const x of String(p||'').replace(/\\/g,'/').split('/')){if(!x||x==='.')continue;if(x==='..'){if(!out.length)throw new Error('Path escapes package root');out.pop()}else out.push(x)}return out.join('/')}
export function validateManifest(m){if(!m||typeof m!=='object')throw new Error('manifest.json must be an object');const id=String(m.id||'').trim();if(!/^[a-z0-9][a-z0-9._-]{1,63}$/i.test(id))throw new Error('Invalid app id');const name=String(m.name||'').trim();if(!name)throw new Error('Missing app name');const entry=normalizePath(m.entry||'index.html');if(!entry)throw new Error('Missing entry');const version=String(m.version||'0.0.0');const permissions=[...new Set((m.permissions||DEFAULT_PERMISSIONS).map(String))];return {...m,id,name,entry,version,dataVersion:Number.isFinite(+m.dataVersion)?+m.dataVersion:1,permissions}}
export function compareVersions(a,b){const pa=String(a).split(/[.+-]/).map(x=>/^\d+$/.test(x)?+x:x),pb=String(b).split(/[.+-]/).map(x=>/^\d+$/.test(x)?+x:x);for(let i=0;i<Math.max(pa.length,pb.length);i++){const x=pa[i]??0,y=pb[i]??0;if(x===y)continue;if(typeof x==='number'&&typeof y==='number')return x>y?1:-1;return String(x)>String(y)?1:-1}return 0}
let table;function crcTable(){if(table)return table;table=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table}
export function crc32(bytes){let c=0xffffffff,t=crcTable();for(const b of bytes)c=t[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
const u16=(a,o,v)=>{a[o]=v&255;a[o+1]=(v>>>8)&255},u32=(a,o,v)=>{u16(a,o,v);u16(a,o+2,v>>>16)};
export function createStoreZip(files){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const f of files){const name=enc.encode(normalizePath(f.path));const data=f.data instanceof Uint8Array?f.data:enc.encode(String(f.data));const crc=crc32(data);const l=new Uint8Array(30+name.length+data.length);u32(l,0,0x04034b50);u16(l,4,20);u16(l,6,0x800);u16(l,8,0);u32(l,14,crc);u32(l,18,data.length);u32(l,22,data.length);u16(l,26,name.length);l.set(name,30);l.set(data,30+name.length);locals.push(l);const c=new Uint8Array(46+name.length);u32(c,0,0x02014b50);u16(c,4,20);u16(c,6,20);u16(c,8,0x800);u16(c,10,0);u32(c,16,crc);u32(c,20,data.length);u32(c,24,data.length);u16(c,28,name.length);u32(c,42,offset);c.set(name,46);centrals.push(c);offset+=l.length}const centralSize=centrals.reduce((n,x)=>n+x.length,0);const e=new Uint8Array(22);u32(e,0,0x06054b50);u16(e,8,files.length);u16(e,10,files.length);u32(e,12,centralSize);u32(e,16,offset);return new Blob([...locals,...centrals,e],{type:'application/zip'})}
export async function parseZip(buffer,inflateRaw){const b=new Uint8Array(buffer),dv=new DataView(b.buffer,b.byteOffset,b.byteLength),dec=new TextDecoder();let e=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(dv.getUint32(i,true)===0x06054b50){e=i;break}if(e<0)throw new Error('Invalid ZIP');const count=dv.getUint16(e+10,true),central=dv.getUint32(e+16,true),files=[];let p=central;for(let i=0;i<count;i++){if(dv.getUint32(p,true)!==0x02014b50)throw new Error('Invalid central directory');const method=dv.getUint16(p+10,true),cs=dv.getUint32(p+20,true),us=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),el=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),lo=dv.getUint32(p+42,true),path=normalizePath(dec.decode(b.slice(p+46,p+46+nl)));p+=46+nl+el+cl;if(!path||path.endsWith('/'))continue;const lnl=dv.getUint16(lo+26,true),lel=dv.getUint16(lo+28,true),start=lo+30+lnl+lel,raw=b.slice(start,start+cs);let data;if(method===0)data=raw;else if(method===8){if(!inflateRaw)throw new Error('Deflate ZIP requires inflater');data=await inflateRaw(raw);if(!(data instanceof Uint8Array))data=new Uint8Array(data)}else throw new Error('Unsupported ZIP compression method '+method);if(data.length!==us)throw new Error('ZIP size mismatch: '+path);files.push({path,data})}return files}
